// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaGcu0Fj58CPEKghC_G1UlaqInaFJ8y6U',
    appId: '1:51026250378:web:ce75533011c6e3aa32bb73',
    messagingSenderId: '51026250378',
    projectId: 'nexusecom-7861',
    authDomain: 'nexusecom-7861.firebaseapp.com',
    databaseURL: 'https://nexusecom-7861-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nexusecom-7861.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcsMekwf8GSpSWUlHYKUyQYiZFT98zoYg',
    appId: '1:51026250378:android:ee1f7e6464689c1b32bb73',
    messagingSenderId: '51026250378',
    projectId: 'nexusecom-7861',
    databaseURL: 'https://nexusecom-7861-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nexusecom-7861.firebasestorage.app',
  );
}
